name: Raspbery Pi 4 Image
on:
  push:
    branches:
      - "main"
      - "ci"

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - run: |
          podman run --pull=always --privileged --rm \
             -v /dev:/dev -v /run/udev:/run/udev -v .:/data -w /data \
             quay.io/coreos/coreos-installer:release \
             download --architecture=aarch64
          unxz $(ls *.xz)
          LOOPDEV=$(losetup -f)
          sudo losetup -P $LOOPDEV $(ls *.raw)
          sudo partprobe $LOOPDEV
          sudo mkdir -p /img/p3
          sudo mount ${LOOPDEV}p3 /img/p3
          ls -lhart /img/p3
          mkdir /img/p3/ignition
          cd images/pi4
          podman run \
            -v $(pwd):/data \
            -i --rm quay.io/coreos/butane:release \
            --pretty \
            -d /data \
            --strict < config.bu > /img/p3/ignition/config.ign
          cp wifi.txt.example /img/p3/
          FCOSEFIPARTITION=${LOOPDEV}p2
          mkdir /tmp/FCOSEFIpart
          sudo mount $FCOSEFIPARTITION /tmp/FCOSEFIpart
          pushd /tmp/FCOSEFIpart
          VERSION=v1.33
          sudo curl -LO https://github.com/pftf/RPi4/releases/download/${VERSION}/RPi4_UEFI_Firmware_${VERSION}.zip
          sudo unzip RPi4_UEFI_Firmware_${VERSION}.zip
          sudo rm RPi4_UEFI_Firmware_${VERSION}.zip
          popd
          sudo umount /tmp/FCOSEFIpart
